### ISSUE TITLE
 mailing-list-archive truncated

### ISSUE THREAD

**Issue by atmodatcode** [cf-convention/mailing-list-archive#3]
Dear Jonathan, 
the CF email archive is very valuable for my work, so I highly appreciate that it is being put here.
I just noted that when opening https://github.com/cf-convention/mailing-list-archive/tree/main/Data
I obtain the warning 
"Sorry, we had to truncate this directory to 1,000 files. 8,890 entries were omitted from the list."
and indeed, there the numbered *.html files in this folder end with 0999.html...
So, it appears that the mail archive is truncated. 
In earlier times, the CF email archive was structured in yearly folders....maybe this is a way to handle the file number limit in GitHub....
Regards
angelika

**Comment by DocOtak** [comment]
Hi @atmodatcode 

That is just how github handles showing source directories with large amounts of files, 

You can access the entire archive on the cf website: http://cfconventions.org/mailing-list-archive/Data/

**Comment by JonathanGregory** [comment]
The mailing list archive is also linked from the [Discussion page](http://cfconventions.org/discussion.html)

**Comment by DocOtak** [comment]
@atmodatcode Feel free to reopen if these answers aren't to your satisfaction.
